development:
  adapter: async
  url: "redis://10.116.0.3:6379/1"

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://10.116.0.3:6379/1" } %>
  channel_prefix: rifamax_central_backend_production
